services:
  - type: web
    name: auto-approval-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app & python3 __main__.py
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: MONGO_URI
        value: your_mongodb_uri
      - key: DB_NAME
        value: AutoApproveDB
      - key: OWNER_ID
        value: your_owner_id
